services:
  - type: web
    name: barpos-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: barpos-db
          property: connectionString
      - key: JWT_SECRET_KEY
        value: supersecret
      - key: SECRET_KEY
        value: anothersecret

  - type: worker 
    name: barpos-migrations 
    env: docker 
    plan: free 
    dockerfilePath: ./Dockerfile 
    command: flask --app backend.app:create_app db upgrade 
    autoDeploy: true

  - type: web
    name: barpos-frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://barpos-backend-sur2.onrender.com

databases:
  - name: barpos-db
    plan: free
