services:
  - type: web
    name: barpos-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:create_app
    releaseCommand: flask --app backend.app:create_app db upgrade
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: barpos-db
          property: connectionString
      - key: JWT_SECRET_KEY
        value: supersecret
      - key: SECRET_KEY
        value: anothersecret

  - type: web
    name: barpos-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://barpos-backend-sur2.onrender.com

databases:
  - name: barpos-db
    plan: free
